### ISSUE TITLE
Invalid File, Can't Import

### ISSUE THREAD

**Issue by jordanranson** [alexander-shch/WebStorm-php-Syntax-Highlight-with-WordPress-functions#1]
When I try and import the .jar file according to the instructions, I get an error: "Invalid File - file.jar contains no settings to import. Please make sure you have generated the file using 'File|Export Settings feature.'

I'm using WebStorm 11.

**Comment by alexander-shch** [comment]
Hi there....

I have exported the new jar file and updated the repo
Please Try again

Also I have added new instructions to the "readme" file 
If the issue continues please refer to the new steps uploading these settings
